In [21]:
import pandas as pd
df = pd.read_csv("onlineFile.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
df.drop('PassengerId', axis=1, inplace=True)

In [9]:
df.drop(3, inplace=True)

In [10]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [18]:
df.set_index("Name", inplace=True)
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",887,0,2,male,27.0,0,0,211536,13.0000,NaN,S
"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S
"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C148,C
"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [19]:
df.reset_index()

,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,"Montvila, Rev. Juozas",887,0,2,male,27.0,0,0,211536,13.0000,NaN,S
887,"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C148,C
890,"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [22]:
df.set_index("Name")

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",887,0,2,male,27.0,0,0,211536,13.0000,NaN,S
"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S
"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C148,C
"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [23]:
df.reset_index()

,index,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [24]:
d = {
    'key1' :[3, 4, 5, 6, 7],
    'key2' :[5, 6, 7, 8, 9],
    'key3' :[1, 2, 3, 4, 5],
}

In [25]:
pd.DataFrame(d)

   key1  key2  key3
0     3     5     1
1     4     6     2
2     5     7     3
3     6     8     4
4     7     9     5

In [26]:
dfo = pd.read_csv("https://docs.google.com/spreadsheets/d/1XJWhtAT0YH_g8aavhkfKI7w96g_9cENG/edit#gid=1242802914")
dfo

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)>

In [27]:
dfo = pd.read_excel("https://docs.google.com/spreadsheets/d/1XJWhtAT0YH_g8aavhkfKI7w96g_9cENG/edit#gid=1242802914")
dfo

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)>

In [28]:
import pandas as pd

# Replace the URL with the CSV export link
google_sheet_url = "https://docs.google.com/spreadsheets/d/1XJWhtAT0YH_g8aavhkfKI7w96g_9cENG/export?format=csv&gid=1242802914"

# Read the Google Sheets data into a pandas DataFrame
df1 = pd.read_csv(google_sheet_url)

# Now df contains your Google Sheets data
print(df1)

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)>

In [31]:
import pandas as pd
import requests

# Replace with your Google Sheets URL
google_sheet_url = "https://docs.google.com/spreadsheets/d/1XJWhtAT0YH_g8aavhkfKI7w96g_9cENG/export?format=csv&gid=1242802914"

# Fetch the CSV content using requests
response = requests.get(google_sheet_url)
print(response)
# Check if the request was successful
if response.status_code == 200:
    # Read the CSV content using pandas
    df = pd.read_excel(response.content)
    print(df)
else:
    print("Failed to fetch data")

<Response [200]>

ValueError: Excel file format cannot be determined, you must specify an engine manually.

In [32]:
import pandas as pd

# Get the Google Sheet ID from the URL
sheet_id = "1XJWhtAT0YH_g8aavhkfKI7w96g_9cENG"

# Read the Google Sheet into a Pandas DataFrame
df = pd.read_csv(f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv")

# Print the DataFrame
print(df)

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)>

In [34]:
pip install gdown

Collecting gdown
  Downloading gdown-4.7.1-py3-none-any.whl (15 kB)
Collecting filelock (from gdown)
  Obtaining dependency information for filelock from https://files.pythonhosted.org/packages/00/45/ec3407adf6f6b5bf867a4462b2b0af27597a26bd3cd6e2534cb6ab029938/filelock-3.12.2-py3-none-any.whl.metadata
  Downloading filelock-3.12.2-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: requests[socks] in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from gdown) (2.31.0)
Requirement already satisfied: six in /Users/vaibhavarde/Library/Python/3.11/lib/python/site-packages (from gdown) (1.16.0)
Collecting tqdm (from gdown)
  Obtaining dependency information for tqdm from https://files.pythonhosted.org/packages/00/e5/f12a80907d0884e6dff9c16d0c0114d81b8cd07dc3ae54c5e962cc83037e/tqdm-4.66.1-py3-none-any.whl.metadata
  Downloading tqdm-4.66.1-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 kB 1.6 MB/s eta 0:00:00
Requirement already satisfied: beautifulsoup4 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from gdown) (4.12.2)
Requirement already satisfied: soupsieve>1.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from beautifulsoup4->gdown) (2.4.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests[socks]->gdown) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests[socks]->gdown) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests[socks]->gdown) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests[socks]->gdown) (2023.7.22)
Collecting PySocks!=1.5.7,>=1.5.6 (from requests[socks]->gdown)
  Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)
Downloading filelock-3.12.2-py3-none-any.whl (10 kB)
Downloading tqdm-4.66.1-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.3/78.3 kB 3.6 MB/s eta 0:00:00
Installing collected packages: tqdm, PySocks, filelock, gdown
Successfully installed PySocks-1.7.1 filelock-3.12.2 gdown-4.7.1 tqdm-4.66.1
Note: you may need to restart the kernel to use updated packages.

In [1]:
import gdown
import pandas as pd

# Replace the URL with the actual sharing link of your Google Sheets document
google_sheets_url = 'https://docs.google.com/spreadsheets/d/1XJWhtAT0YH_g8aavhkfKI7w96g_9cENG/export?format=csv&gid=1242802914'
csv_file_path = 'data.csv'
gdown.download(google_sheets_url, csv_file_path, quiet=False)
df = pd.read_csv(csv_file_path)

# Display the DataFrame
print(df)

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gdown/parse_url.py:44: UserWarning: You specified a Google Drive link that is not the correct link to download a file. You might want to try `--fuzzy` option or the following url: https://drive.google.com/uc?id=None
  warnings.warn(
Downloading...
From: https://docs.google.com/spreadsheets/d/1XJWhtAT0YH_g8aavhkfKI7w96g_9cENG/export?format=csv&gid=1242802914
To: /Users/vaibhavarde/Desktop/VaibhaV/learnPython/learnPandas/data.csv
14.8kB [00:00, 17.2MB/s]

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency       NaN                   NaN
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3    0101-02-01             Help Pay for Food    101-02        Emergency Cash
4    0101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285  0111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [2]:
df1 = pd.read_csv("data.csv")
df1

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency       NaN                   NaN
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3    0101-02-01             Help Pay for Food    101-02        Emergency Cash
4    0101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285  0111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [12]:
print(len(df1))
df1.dropna(inplace=True)
print(len(df1))
df1

279
279

    taxonomy_id                          name parent_id           parent_name
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3    0101-02-01             Help Pay for Food    101-02        Emergency Cash
4    0101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
5    0101-02-03          Help Pay for Housing    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285  0111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[279 rows x 4 columns]

In [14]:
df2 = pd.read_csv("data.csv")
df2

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency       NaN                   NaN
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3    0101-02-01             Help Pay for Food    101-02        Emergency Cash
4    0101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285  0111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [15]:
print(len(df2.columns))
df2.dropna(axis=1, inplace=True)
print(len(df2.columns))

4
2

In [16]:
df3 = pd.read_csv("data.csv")
df3

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency       NaN                   NaN
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3    0101-02-01             Help Pay for Food    101-02        Emergency Cash
4    0101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285  0111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [17]:
df3.fillna("VaibhaV")

    taxonomy_id                          name parent_id           parent_name
0           101                     Emergency   VaibhaV               VaibhaV
1        101-01             Disaster Response       101             Emergency
2        101-02                Emergency Cash       101             Emergency
3    0101-02-01             Help Pay for Food    101-02        Emergency Cash
4    0101-02-02       Help Pay for Healthcare    101-02        Emergency Cash
..          ...                           ...       ...                   ...
285  0111-01-07              Workplace Rights    111-01  Advocacy & Legal Aid
286      111-02                     Mediation       111                 Legal
287      111-03                        Notary       111                 Legal
288      111-04                Representation       111                 Legal
289      111-05  Translation & Interpretation       111                 Legal

[290 rows x 4 columns]

In [34]:
dfg = pd.read_csv("onlineFile.csv")
dfg.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [24]:
g = dfg.groupby('Sex')

In [22]:
g.sum()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Sex,,,,,,,,,,,
female,135343,233,678,"Cumings, Mrs. John Bradley (Florence Briggs Th...",7286.00,218,204,PC 17599STON/O2. 3101282113803347742237736PP 9...,13966.6628,C85C123G6C103B78D33B28F33C23 C25 C27E101F E69D...,CSSSCSSSSSCQSSQCQSCSSCQQSCSSSSSSSQSSSSSSQCSCSS...
male,262043,109,1379,"Braund, Mr. Owen HarrisAllen, Mr. William Henr...",13919.17,248,136,A/5 2117137345033087717463349909A/5. 215134708...,14727.2865,E46D56A6C23 C25 C27B30C52C83F G73E31A5D10 D12D...,SSQSSSSQSSSSCSSCSCSCSCSQCSSCSCSCSSCCSSSSCSSSSS...

In [35]:
g1= dfg.groupby('Pclass')

In [36]:
g1.sum(numeric_only=True)

        PassengerId  Survived      Age  SibSp  Parch        Fare
Pclass
1             99705       136  7111.42     90     77  18177.4125
2             82056        87  5168.83     74     70   3801.8417
3            215625       119  8924.92    302    193   6714.6951

In [37]:
g1.mean(numeric_only=True)

        PassengerId  Survived        Age     SibSp     Parch       Fare
Pclass
1        461.597222  0.629630  38.233441  0.416667  0.356481  84.154687
2        445.956522  0.472826  29.877630  0.402174  0.380435  20.662183
3        439.154786  0.242363  25.140620  0.615071  0.393075  13.675550

In [38]:
g1.max(numeric_only=True)

        PassengerId  Survived   Age  SibSp  Parch      Fare
Pclass
1               890         1  80.0      3      4  512.3292
2               887         1  70.0      3      3   73.5000
3               891         1  74.0      8      6   69.5500

In [53]:
g1.max(numeric_only=True).transpose()

Pclass              1      2
PassengerId  890.0000  887.0
Survived       1.0000    1.0
Age           80.0000   70.0
SibSp          3.0000    3.0
Parch          4.0000    3.0
Fare         512.3292   73.5

In [48]:
g1.mean(numeric_only=True)['Fare']

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64